name = "lean-playground"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeanPlayground"]

[leanOptions]
pp.unicode.fun = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.2"

[[lean_lib]]
name = "LeanPlayground"
roots = ["LeanPlayground", "Logic", "NNG", "SetTheoryGame", "Type"]
